id: IA5505A8D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T11:56:49+00:00'
last_modified: '2022-06-08T03:37:44.999415+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD97741
  title: བྱམས་པའི་གསེར་ཟངས་ཀྱི་སྐུ་བརྙན་མཚོ་གཟིགས་སྲིད་གསུམ་མཛེས་པའི་རྒྱན་མཆོག་གི་དཀར་ཆག་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    7BA5:
      image_group_id: I1PD97745
      title: ''
      total_pages: 38
      order: 1
      base_file: 7BA5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
