id: P005514
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD97741
  title: བྱམས་པའི་གསེར་ཟངས་ཀྱི་སྐུ་བརྙན་མཚོ་གཟིགས་སྲིད་གསུམ་མཛེས་པའི་རྒྱན་མཆོག་གི་དཀར་ཆག་
  author: ''
  volumes:
    77db86b9923a45aaaf066248f25c60d6:
      image_group_id: I1PD97745
      title: ''
      volume_number: 1
      total_pages: 38
      base_file: v001.txt
